In [11]:
import cv2
import numpy as np

In [12]:
cap = cv2.VideoCapture('sample 30 frame 1 min.mp4')
if (cap.isOpened()== False): 
    print("Error opening video stream or file")

gray_frames = []    
while(cap.isOpened()):
  
    ret, frame = cap.read()
    if ret == True:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray_frames.append(gray)
        cv2.imshow('Frame', gray)

        if cv2.waitKey(25) & 0xFF == ord('q'):
            break
    else: 
        break

cap.release()
cv2.destroyAllWindows()

In [21]:
print(gray_frames[0].shape)

(540, 960)


In [29]:
# from scipy.fft import fft, dct
from scipy.fftpack import fft, dct

In [30]:
block_width = 8
block_height = 8

num_frames = len(gray_frames)
transformed_frames = []

print(gray_frames[0])

for f in range(num_frames):
    current_frame = gray_frames[f]
    current_frame_transformed = np.empty_like(current_frame)
    frame_height, frame_width = current_frame.shape
    
    for i in range(0, frame_height, block_height):
        for j in range(0, frame_width, block_width):
            current_block = current_frame[i: i + block_height, j: j + block_width]
            transformed_current_block = dct(current_block)
            current_frame_transformed[i: i + block_height, j: j + block_width] = transformed_current_block
    transformed_frames.append(current_frame_transformed)

print(transformed_frames[0])

[[ 59  96 118 ... 141 108  65]
 [ 75 113 137 ... 164 131  88]
 [ 74 113 142 ... 162 129  86]
 ...
 [ 64 107 142 ... 144 122  85]
 [ 68 109 141 ... 143 121  84]
 [ 53  93 123 ... 124 102  65]]
[[206  94 131 ...  14  11 247]
 [ 18  68 122 ...  20  11 242]
 [ 28  81 103 ...  20  11 242]
 ...
 [  2  44  83 ...  29 255 249]
 [  6  55  97 ...  33   0 245]
 [210  83 103 ...  24 255 253]]


# Resources & References

1. https://learnopencv.com/read-write-and-display-a-video-using-opencv-cpp-python/
2. https://docs.opencv.org/master/dd/d43/tutorial_py_video_display.html
3. https://ottverse.com/discrete-cosine-transform-dct-video-compression/
4. https://yasoob.me/posts/understanding-and-writing-jpeg-decoder-in-python/
5. https://docs.scipy.org/doc/scipy/reference/generated/scipy.fftpack.dct.html#scipy.fftpack.dct
6. https://docs.scipy.org/doc/scipy/reference/fftpack.html
7. https://fairyonice.github.io/2D-DCT.html